name: Deploy to GCP

on:
  push:
    branches:
      - feature/add-pyspark
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Sync Files to GCS
      run: |
        # Force the project context
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        
        # Use gsutil to sync your folders
        # IMPORTANT: Replace 'your-actual-bucket-name' with your GCS bucket name
        gsutil -m rsync -r ./dags gs://your-actual-bucket-name/dags
        gsutil -m rsync -r ./pyspark gs://your-actual-bucket-name/pyspark
        gsutil -m rsync -r ./sql gs://your-actual-bucket-name/sql