name: Deploy to GCP

on:
  push:
    branches:
      - feature/add-pyspark
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Sync Files to GCS
      run: |
        # Ensure the project is set correctly
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        
        # Syncing your local folders to your specific bucket
        gsutil -m rsync -r ./dags gs://my-first-bucket-1210/dags
        gsutil -m rsync -r ./pyspark gs://my-first-bucket-1210/pyspark
        gsutil -m rsync -r ./sql gs://my-first-bucket-1210/sql